### ISSUE TITLE
Failed to open file "CRA_test1_mgatk/temp/temp_bam/barcodes.8.temp0.bam" : No such file or directory

### ISSUE THREAD

**Issue by bio-ruxandra-tesloianu** [caleblareau/mgatk#30]
Hi,

I am running mgatk tenx as advised in the documentation:

mgatk tenx -i $folder_bam/possorted_bam.bam  -n CRA_test1 -o CRA_test1_mgatk -c 12 -bt CB -b $folder_bam/filtered_peak_bc_matrix/barcodes.tsv

I get the following error:

Error in checkGrep(grep(".A.txt", files)) : 
  Improper folder specification; file missing / extra file present. See documentation
Calls: importMito -> checkGrep
Execution halted
(myenv)jovyan@jupyter-bio-2druxandra-2dtesloianu:~$ [E::hts_open_format] Failed to open file "CRA_test1_mgatk/temp/temp_bam/barcodes.8.temp0.bam" : No such file or directory
[Sat Nov  7 14:38:19 2020]
Error in rule process_one_slice:
    jobid: 0
    output: CRA_test1_mgatk/qc/depth/barcodes.8.depth.txt, CRA_test1_mgatk/temp/sparse_matrices/barcodes.8.A.txt, CRA_test1_mgatk/temp/sparse_matrices/barcodes.8.C.txt, CRA_test1_mgatk/temp/sparse_matrices/barcodes.8.G.txt, CRA_test1_mgatk/temp/sparse_matrices/barcodes.8.T.txt, CRA_test1_mgatk/temp/sparse_matrices/barcodes.8.coverage.txt

RuleException:
SamtoolsError in line 93 of /home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx:
'samtools returned with error 1: stdout=, stderr=samtools sort: can\'t open "CRA_test1_mgatk/temp/temp_bam/barcodes.8.temp0.bam": No such file or directory\n'
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2252, in run_wrapper
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx", line 93, in __rule_process_one_slice
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2264, in run_wrapper
Exiting because a job execution failed. Look above for error message
[E::hts_open_format] Failed to open file "CRA_test1_mgatk/temp/temp_bam/barcodes.4.temp0.bam" : No such file or directory

When I do ls -lR on the CRA_test1_mgatk directory, it seems like it completely lacks the temp directory 

(myenv)jovyan@jupyter-bio-2druxandra-2dtesloianu:~/CRA_test1_mgatk$ ls -lR
.:
total 12
drwxr-sr-x 2 jovyan users 4096 Nov  7 13:05 final
drwxr-sr-x 4 jovyan users 4096 Nov  7 13:11 logs
drwxr-sr-x 3 jovyan users 4096 Nov  7 14:38 qc

./final:
total 120
-rw-r--r-- 1 jovyan users 121446 Nov  7 14:31 chrM_refAllele.txt

./logs:
total 16
-rw-r--r-- 1 jovyan users 1392 Nov  7 14:37 base.mgatk.log
-rw-r--r-- 1 jovyan users  602 Nov  7 14:37 CRA_test1.parameters.txt
-rw-r--r-- 1 jovyan users    0 Nov  7 14:37 CRA_test1.snakemake_tenx.log
drwxr-sr-x 2 jovyan users 4096 Nov  7 14:26 filterlogs
drwxr-sr-x 2 jovyan users 4096 Nov  7 13:11 rmdupslogs

./logs/filterlogs:
total 96
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.10.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.11.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.12.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:25 barcodes.13.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.14.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.15.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.16.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.17.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:25 barcodes.18.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:25 barcodes.19.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.1.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:25 barcodes.20.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.21.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.22.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.23.filter.log
-rw-r--r-- 1 jovyan users 24 Nov  7 14:26 barcodes.24.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.2.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.3.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.4.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.5.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.6.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.7.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.8.filter.log
-rw-r--r-- 1 jovyan users 26 Nov  7 14:38 barcodes.9.filter.log

./logs/rmdupslogs:
total 0

./qc:
total 4
drwxr-sr-x 2 jovyan users 4096 Nov  7 13:11 quality

./qc/quality:
total 0

**Comment by caleblareau** [comment]
hey sorry @bio-ruxandra-tesloianu somehow I missed seeing this-- did this get resolved somehow?

**Comment by bio-ruxandra-tesloianu** [comment]
> hey sorry @bio-ruxandra-tesloianu somehow I missed seeing this-- did this get resolved somehow?

no :(

**Comment by caleblareau** [comment]
Could you `cat` the `*logs/filterlogs*` files? 

we recently made some tweaks to `tenx` mode-- could you try running with version 0.6.0 (latest on Pypi) and let me know if anything gets better?

**Comment by pk43429** [comment]
Hi @caleblareau,

I got the same error while running with version 0.6.1. Here is the output for `cat` the `*logs/filterlogs*`:

```
Kept 715654
Removed 5450
Kept 670028
Removed 5264
Kept 681359
Removed 5555
Kept 790015
Removed 6727
Kept 662046
Removed 6125
Kept 773335
Removed 6794
Kept 659653
Removed 5663
Kept 697615
Removed 6022
Kept 729339
Removed 6202
Kept 666933
Removed 5954
Kept 646504
Removed 5592
Kept 686152
```

**Comment by caleblareau** [comment]
And you're still getting an error associated with 
```
SamtoolsError in line 93 of /home/jovyan/my-conda-envs/myenv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx:
'samtools returned with error 1: stdout=, stderr=samtools sort: can't open
```

?

It looks like the filtering is working as we would expect but the resulting bam file isn't being output... Can you try the same execution with the `bcall` mode and see if anything changes?

**Comment by cnk113** [comment]
Hmm, so I also am running into this after installing mgatk (0.6.1) on a new system.
```
Error in rule process_one_slice:                                                                                                                                                                                     jobid: 0                                                                                                                                                                                                         output: mgatk_out/qc/depth/barcodes.29.depth.txt, mgatk_out/temp/sparse_matrices/barcodes.29.A.txt, mgatk_out/temp/sparse_matrices/barcodes.29.C.txt, mgatk_out/temp/sparse_matrices/barcodes.29.G.txt, mgatk_out/temp/sparse_matrices/barcodes.29.T.txt, mgatk_out/temp/sparse_matrices/barcodes.29.coverage.txt                                                                                                                                                                                                                                                                                                                              RuleException:                                                                                                                                                                                                   OSError in line 113 of /home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx:                                                                                              No such file or directory: 'mgatk_out/temp/ready_bam/barcodes.29.qc.bam'                                                                                                                                           File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2352, in run_wrapper                                                                                   File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx", line 113, in __rule_process_one_slice                                                                        File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pysam/utils.py", line 61, in __call__                                                                                                         File "pysam/libcutils.pyx", line 293, in pysam.libcutils._pysam_dispatch                                                                                                                                         File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 569, in _callback                                                                                      File "/home/chang/miniconda3/envs/venv/lib/python3.7/concurrent/futures/thread.py", line 57, in run                                                                                                              File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 555, in cached_or_run                                                                                  File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2364, in run_wrapper 
```
Run command
```
 mgatk tenx -i possorted_bam.bam -b filtered_peak_bc_matrix/barcodes.tsv -bt CB -o mgatk_out -c 48 --snake-stdout --keep-temp-files
```
I'm running bcall right now, but it's definitely taking much longer than usual.

**Comment by cnk113** [comment]
Ok here is the bcall error:
```
Traceback (most recent call last):                                                                                                                                                                                 File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/mgatk/bin/python/oneSample.py", line 82, in <module>                                                                                            pysam.index(outputbam)                                                                                                                                                                                         File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/pysam/utils.py", line 61, in __call__                                                                                                           save_stdout=kwargs.get("save_stdout", None))                                                                                                                                                                   File "pysam/libcutils.pyx", line 293, in pysam.libcutils._pysam_dispatch                                                                                                                                       OSError: No such file or directory: 'mgatk_out/temp/ready_bam/ACGCCACGTTGTGGTT-1.qc.bam'
```
```
MissingOutputException in line 21 of /home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.Scatter:                                                                             Job Missing files after 5 seconds:                                                                                                                                                                               mgatk_out/temp/ready_bam/ACGCCACGTTGTGGTT-1.qc.bam                                                                                                                                                               mgatk_out/temp/ready_bam/ACGCCACGTTGTGGTT-1.qc.bam.bai
mgatk_out/qc/depth/ACGCCACGTTGTGGTT-1.depth.txt                                                                                                                                                                  mgatk_out/temp/sparse_matrices/ACGCCACGTTGTGGTT-1.A.txt
mgatk_out/temp/sparse_matrices/ACGCCACGTTGTGGTT-1.C.txt                                                                                                                                                          mgatk_out/temp/sparse_matrices/ACGCCACGTTGTGGTT-1.G.txt                                                                                                                                                          mgatk_out/temp/sparse_matrices/ACGCCACGTTGTGGTT-1.T.txt                                                                                                                                                          mgatk_out/temp/sparse_matrices/ACGCCACGTTGTGGTT-1.coverage.txt                                                                                                                                                   This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.                                                                                            Job id: 0 completed successfully, but some output files are missing. 0                                                                                                                                             File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 584, in handle_job_success                                                                             File "/home/chang/miniconda3/envs/venv/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 259, in handle_job_success                                                                           Exiting because a job execution failed. Look above for error message 
```

**Comment by caleblareau** [comment]
So `bcall` will take much longer in general than `tenx` mode. If you want to trouble shoot, just supply a shorter list of barcodes (e.g. `head filtered_peak_bc_matrix/barcodes.tsv > short.tsv`; then supply `-b short.tsv`

Anywho, I'm not sure that I see a consistent error here compared to what it previously was. You verified java, which is great. Can you send `ls -lR` of the mgatk output folder?

**Comment by cnk113** [comment]
[Log.txt](https://github.com/caleblareau/mgatk/files/6470920/Log.txt)
Here's the output dir.

**Comment by caleblareau** [comment]
just to verify @cnk113 did the pipeline work on the test data? It looks liek the per-sample processing just stopped randomly at some point in the cell processing, which is extremely unusual. I don't think that I've seen this behavior before...

**Comment by cnk113** [comment]
Oops, that was my old one, here's the one with a few bcs.
[Log.txt](https://github.com/caleblareau/mgatk/files/6471076/Log.txt)

**Comment by bio-ruxandra-tesloianu** [comment]
I am quite late here but my error was solved by doing snake stdout at the end of the command

**Comment by cnk113** [comment]
I ran it with snake stdout. I've previously solved an earlier issue like that. This is new.

**Comment by cnk113** [comment]
So I've been trying to debug this, and tried this multiple different Ubuntu versions and python version/env.
From what I understand, everything is fine until filterClipBam which ends up not printing the bam file (I can see it run in htop but almost instantaneously fails)

**Comment by cnk113** [comment]
Ok I found the issue:
```
Exception in thread "main" picard.PicardException: This program requires input that are either coordinate or query sorted (according to the header, or at least ASSUME_SORT_ORDER and the content.) Found ASSUME_SORT_ORDER=null and header sortorder=unsorted                                                                                                                                                                            at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:294)                                                                                                                                      at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)                                                                                                                                   at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)                                                                                                                                     at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
```
Pretty much it seems the header showed unsorted even though it was sorted through pysam sort.
I just added ASSUME_SORTED=true to your picard command and it works.


However I now get a different error towards the end (almost there!)
```
Traceback (most recent call last):                                                                                                                                                                                 
File "/media/chang/HDD-6/chang/mg/atac/Adult_DSP_MG_multi_atac_cr/outs/mgatk/mgatk/bin/python/variant_calling.py", line 88, in <module> base_coverage_dict = load_mgatk_output(MGATK_OUT_DIR)
File "/media/chang/HDD-6/chang/mg/atac/Adult_DSP_MG_multi_atac_cr/outs/mgatk/mgatk/bin/python/variant_calling.py", line 30, in load_mgatk_output fwd_base_df[missing_pos] = 0  # fill in missing positions                                                                                                                                                    
File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2935, in __setitem__                                                                                             self._setitem_array(key, value)                                                                                                                                                                               
File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2966, in _setitem_array                                                                                          key, axis=1, raise_missing=False
File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/pandas/core/indexing.py", line 1553, in _get_listlike_indexer keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing                                                                                                                                         
File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/pandas/core/indexing.py", line 1640, in _validate_read_indexer raise KeyError(f"None of [{key}] are in the [{axis_name}]")                                                                                                                                                  
KeyError: "None of [Int64Index([    1,     3,     4,     6,     8,     9,    10,    11,    12,\n               14,\n            ...\n            16551, 16555, 16558, 16560, 16562, 16563, 16565, 16566, 16568,\n            16569],\n           dtype='int64', length=11090)] are in the [columns]"                                                                                                                              
MissingOutputException in line 163 of /media/chang/HDD-6/chang/mg/atac/Adult_DSP_MG_multi_atac_cr/outs/mgatk/mgatk/bin/snake/Snakefile.tenx:                                                                    
Job Missing files after 5 seconds:                                                                                                                                                                               mgatk_out/final/mgatk.variant_stats.tsv.gz                                                                                                                                                                       mgatk_out/final/mgatk.cell_heteroplasmic_df.tsv.gz                                                                                                                                                               mgatk_out/final/mgatk.vmr_strand_plot.png                                                                                                                                                                        This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.                                                                                            Job id: 0 completed successfully, but some output files are missing. 0                                                                                                                                             File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 589, in handle_job_success                                                                          
File "/home/chang/miniconda3/envs/venv3.6/lib/python3.6/site-packages/snakemake/executors/__init__.py", line 259, in handle_job_success  
```
[Uploading 2021-05-28T214711.286892.snakemake.log…]()

**Comment by cnk113** [comment]
Ok so the latest error seems to be sample specific, I'm assuming no variant was confidently detected or there wasn't enough MT coverage.

**Comment by rpolicastro** [comment]
I just wanted to add that I get the same error with failing to find the bam file.

**Comment by caleblareau** [comment]
Implemented this fix in v0.6.3-- hopefully this solves things, but please comment on thread if not!

**Comment by mvinyard** [comment]
Hi @caleblareau - thanks for making this great tool. I am encountering the same issue using `v0.6.4` where the files in `mgatk_out/temp/` seem to be called after they are deleted. I read through this thread but the implemented solution does not seem to carry over for me - please excuse me if I am missing a key detail. 

**Using**:
- OS: Ubuntu LTS 20.04
- python: `3.7.12`
- R: `4.1.2`
- `cellranger-atac-2.0.0`

I've included all of the outputs of `mgatk` below - I am happy to supply any other potentially useful information. 

**Command**: 
```BASH
mgatk tenx --input outs/possorted_bam.bam -bt CB -b outs/filtered_peak_bc_matrix/mini.tsv --mito-genome hg38 --ncores=14
```

---

**Error message**
<details>

```BASH
[Thu Dec 23 21:22:31 2021]
Error in rule process_one_slice:
    jobid: 0
    output: mgatk_out/qc/depth/barcodes.8.depth.txt, mgatk_out/temp/sparse_matrices/barcodes.8.A.txt, mgatk_out/temp/sparse_matrices/barcodes.8.C.txt, mgatk_out/temp/sparse_matrices/barcodes.8.G.txt, mgatk_out/temp/sparse_matrices/barcodes.8.T.txt, mgatk_out/temp/sparse_matrices/barcodes.8.coverage.txt

RuleException:
OSError in line 113 of /home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx:
No such file or directory: 'mgatk_out/temp/ready_bam/barcodes.8.qc.bam'
  File "/home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/site-packages/mgatk/bin/snake/Snakefile.tenx", line 113, in __rule_process_one_slice
  File "/home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/site-packages/pysam/utils.py", line 61, in __call__
  File "pysam/libcutils.pyx", line 323, in pysam.libcutils._pysam_dispatch
  File "/home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mvinyard/data/test_sample/.snakemake/log/2021-12-23T212219.494102.snakemake.log
```
</details>

---

**`find ./mgatk_out/`** produces the following file structure:

<details>

```
mgatk_out
mgatk_out/final
mgatk_out/final/chrM_refAllele.txt
mgatk_out/qc
mgatk_out/qc/quality
mgatk_out/logs
mgatk_out/logs/mgatk.parameters.txt
mgatk_out/logs/rmdupslogs
mgatk_out/logs/base.mgatk.log
mgatk_out/logs/mgatk.snakemake_tenx.log
mgatk_out/logs/filterlogs
mgatk_out/logs/filterlogs/barcodes.5.filter.log
mgatk_out/logs/filterlogs/barcodes.7.filter.log
mgatk_out/logs/filterlogs/barcodes.6.filter.log
mgatk_out/logs/filterlogs/barcodes.3.filter.log
mgatk_out/logs/filterlogs/barcodes.4.filter.log
mgatk_out/logs/filterlogs/barcodes.2.filter.log
mgatk_out/logs/filterlogs/barcodes.10.filter.log
mgatk_out/logs/filterlogs/barcodes.8.filter.log
mgatk_out/logs/filterlogs/barcodes.1.filter.log
mgatk_out/logs/filterlogs/barcodes.9.filter.log
```
</details>

---

**`cat base.mgatk.log`** produces:

<details>

```
Thu Dec 23 21:22:17 UTC 2021: Starting analysis with mgatk
Thu Dec 23 21:22:17 UTC 2021: Processing samples with 14 threads
Thu Dec 23 21:22:17 UTC 2021: mgatk successfully processed the supplied .bam files
Thu Dec 23 21:22:26 UTC 2021: Successfully created final output files
Thu Dec 23 21:22:26 UTC 2021: Intermediate files successfully removed.
```
</details>

---

**` cat filterlogs/*`** produces:
<details>

```
Kept 35386
Removed 25
Kept 23104
Removed 11
Kept 51542
Removed 19
Kept 42683
Removed 39
Kept 86645
Removed 37
Kept 18473
Removed 11
Kept 211905
Removed 136
Kept 66058
Removed 38
Kept 90319
Removed 53
Kept 33776
Removed 31
```
</details>

---

**`cat mgatk.parameters.txt`** produces:
<details>

```
input_directory: 'outs/possorted_bam.bam'
output_directory: 'mgatk_out'
script_dir: '/home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/site-packages/mgatk'
fasta_file: '/home/mvinyard/.anaconda3/envs/mgatk/lib/python3.7/site-packages/mgatk/bin/anno/fasta/hg38.fasta'
mito_chr: 'chrM'
mito_length: '16569'
name: 'mgatk'
base_qual: '0'
remove_duplicates: 'True'
handle_overlap: 'False'
low_coverage_threshold: '10'
barcode_tag: 'CB'
umi_barcode: 'MU'
alignment_quality: '0'
emit_base_qualities: 'False'
proper_paired: 'False'
NHmax: '1'
NMmax: '4'
max_javamem: '8000m'
```
</details>

---

**`cat mgatk.snakemake_tenx.log `** produces nothing.

Probably unnecessary but just in case, **`cat mgatk_out/final/chrM_refAllele.txt | head -10`** produces:
<details>

```
1       G
2       A
3       T
4       C
5       A
6       C
7       A
8       G
9       G
10      T
```
</details>

---

I think that's everything - I will keep trouble-shooting in the meantime and provide an update if I find a solution. Thanks in advance for your time and any potential help!

**Comment by caleblareau** [comment]
Can you try with `--snake-stdout` ?

**Comment by mvinyard** [comment]
> Can you try with `--snake-stdout` ?

Ah this seems to clear up the issue.  

I saw it mentioned above 
> I ran it with snake stdout. I've previously solved an earlier issue like that. This is new.

but thought this would be a separate case. I'm not sure why the snakemake workflow requires that but it's enough for me. I am currently testing the outputs in downstream workflows. Thanks for your help, Caleb!

**Comment by caleblareau** [comment]
I have no idea either but glad it's working now :)
