### ISSUE TITLE
Python unicode error

### ISSUE THREAD

**Issue by ollieeknight** [caleblareau/mgatk#45]
Heya Caleb,

Thanks so much for this package, super useful and interesting. I was wondering if you could help me, with the error, below;

```
Traceback (most recent call last):
  File "/u/oknight/bin/miniconda3/bin/mgatk", line 8, in <module>
    sys.exit(main())
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/mgatk/cli.py", line 208, in main
    barcode_files = split_barcodes_file(barcodes, math.ceil(file_len(barcodes)/int(ncores)), output)
  File "/u/oknight/bin/miniconda3/lib/python3.9/site-packages/mgatk/mgatkHelp.py", line 167, in file_len
    for i, l in enumerate(f):
  File "/u/oknight/bin/miniconda3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Thanks a million

Ollie

**Comment by caleblareau** [comment]
Hmm I don't think I've seen this before.

https://stackoverflow.com/questions/44659851/unicodedecodeerror-utf-8-codec-cant-decode-byte-0x8b-in-position-1-invalid/44660123

This is the error

Can you share your command and verify that the tes  data worked for you?

**Comment by ollieeknight** [comment]
it's worked perfectly on your test data.

my script is (with sample ID's removed);

`mgatk tenx -i Sample/outs/atac_possorted_bam.bam -n Sample -o sample_mgatk -bt CB -b path/outs/filtered_feature_bc_matrix/barcodes.tsv.gz`

these are generated through the cellranger arc 2.0.0 pipeline, from a 10x multiome experiment, using a ref genome we hardmasked mitochondrial regions of and then run cellranger mkref with. all of the outs from the cellranger pipeline looked good, so far.

**Comment by caleblareau** [comment]
Can you unzip the barcodes file? I should add that as a feature but currently I don’t have support for that

**Comment by ollieeknight** [comment]
Great! I think that's done the trick. I gunzip'd barcodes.tsv.gz and changed the script to run directly on barcodes.tsv.

Appreciate the help!

**Comment by caleblareau** [comment]
sure thing-- I will fix this in the coming versions. glad this work around fixed things though
