### ISSUE TITLE
importMito error

### ISSUE THREAD

**Issue by FionaMoon** [caleblareau/mgatk#80]
Hi,

I met an error like this when processing one of my scRNA-seq data, which never happened before.
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'levels': subscript out of bounds
Calls: importMito ... [[.data.frame -> <Anonymous> -> .handleSimpleError -> h
Execution halted
```
I don't know whether this error is caused by my data or it's a bug of mgatk.

Thank you in advance.

**Comment by FionaMoon** [comment]
The log file of snakemake looks like this:
```
Traceback (most recent call last):
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/mgatk/bin/python/variant_calling.py", line 90, in <module>
    base_coverage_dict = load_mgatk_output(MGATK_OUT_DIR, mito_length)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/mgatk/bin/python/variant_calling.py", line 23, in load_mgatk_output
    cur_base_data = pd.read_csv(gzip.open(base_files[i]), header=None)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Waiting at most 5 seconds for missing files.
MissingOutputException in rule call_variants in file /public/home/peishanshangroup/liangy/miniconda3/envs/mgatk/lib/python3.8/site-packages/mgatk/bin/snake/Snakefile.tenx, line 160:
Job 0 completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
SRR24572674_mgatk/final/SRR24572674.variant_stats.tsv.gz
SRR24572674_mgatk/final/SRR24572674.cell_heteroplasmic_df.tsv.gz
SRR24572674_mgatk/final/SRR24572674.vmr_strand_plot.png
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

```

**Comment by dstyaaaaaa** [comment]
I have the same problem. I wonder how this problem came about and how it was solved. Thanks!

**Comment by JHYSiu** [comment]
I have run into the same problem. Also wondering if there's a solution to this problem...thanks!
