### ISSUE TITLE
Too many opened files 

### ISSUE THREAD

**Issue by MagpiePKU** [caleblareau/mgatk#81]
**Describe the bug**

mgatk bcall results in 'Too many open files' error. 

I wonder if we can arbitrarily set the limit of opened threads in the script? 

**To Reproduce**
Command to reproduce the behavior: 

/gpfs/bin/anaconda3-loompy/bin/mgatk bcall \
-i $inputbam \
-n `basename $inputbam .bam`.MGATK \
-o `basename $inputbam .bam`.MGATK_output \
-g mm10 \
-c 5 \
-bt CB \
-mb 1000 \
-z \

** The error persists when -c is changed from 20 to 1 (the node has 48 cores). 

File size of BAM range from 200M to 500M reads. There are around 16k cells (in the passingBarcodes.tsv) in each BAM file.  At the moment of error, lsof give rise to a huge number of opened files like 10k+. 

**Expected behavior**

The error log as:
```
Traceback (most recent call last):
  File "/gpfs/bin/anaconda3-loompy/lib/python3.8/site-packages/mgatk/bin/python/split_barcoded_bam.py", line 64, in <module>
    with multi_file_manager(bambcfiles) as fopen:
  File "/gpfs/bin/anaconda3-loompy/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/gpfs/bin/anaconda3-loompy/lib/python3.8/site-packages/mgatk/bin/python/split_barcoded_bam.py", line 56, in multi_file_manager
    files = [pysam.AlignmentFile(file, "wb", template = temp) for file in files]
  File "/gpfs/bin/anaconda3-loompy/lib/python3.8/site-packages/mgatk/bin/python/split_barcoded_bam.py", line 56, in <listcomp>
    files = [pysam.AlignmentFile(file, "wb", template = temp) for file in files]
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 915, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 24] could not open alignment file `pipeline.output.step3.MGATK_output/temp/barcoded_bams/GCTCGGTAACCACTGTCAATGGAA.bam`: Too many open files
```

**Desktop (please complete the following information):**
 - OS: CentOS 7 
- CPU: x86_64 48 cores

**Comment by MagpiePKU** [comment]
Nevermind. Found this could be solved with -ns parameter. Thanks a lot!
