### ISSUE TITLE
Error in checkGrep(grep(".A.txt", files)) and Attribute error in 'pulp'

### ISSUE THREAD

**Issue by davhg96** [caleblareau/mgatk#93]
**Describe the bug**

Hi, Im trying to run mgatk on a tenx run I did using the dogmaseq protocol. 
When running:
`mgatk tenx -i ./PATHTO/atac_possorted_bam.bam -n mtMSC  -o /PATHTOOUT/mtMSC -bt CB -b /PATHTOBarcodes/barcodes.tsv`

And I get

`Thu May 23 15:38:01 CEST 2024: mgatk v0.7.0

Thu May 23 15:38:01 CEST 2024: Found bam file: /3_Data/InVitroDogma/atac_possorted_bam.bam for genotyping.
Thu May 23 15:38:01 CEST 2024: Found file of barcodes to be parsed: ./3_Data/InVitroDogma/barcodes.tsv
Thu May 23 15:38:01 CEST 2024: User specified mitochondrial genome matches .bam file 
Thu May 23 15:38:11 CEST 2024: Finished determining/splitting barcodes for genotyping.
Thu May 23 15:38:12 CEST 2024: Genotyping samples with 20 threads
Traceback (most recent call last):
File "/opt/mamba24/bin/snakemake", line 8, in <module> sys.exit(main())
File "/opt/mamba24/lib/python3.10/site-packages/snakemake/_init_.py", line 2736, in main parser get_argument_parser()
File "/opt/mamba24/lib/python3.10/site-packages/snakemake/_init__.py", line 1607, in get_argument_parser lp_solvers pulp.list_solvers(onlyAvailable True)
AttributeError: module 'pulp' has no attribute 'list solvers'. Did you mean: 'ListSolvers'? Improper folder specification; file missing / extra file present. See documentation
Error in checkGrep(grep(".A.txt", files)):

Calls: importMito -> checkGrep
Execution halted`

**A summary of .log files**
Output of the Log files

cat logs/*log |  
-- | --
  | Thu May 23 15:29:28 CEST 2024: Starting analysis with mgatk
  | Thu May 23 15:29:28 CEST 2024: Processing samples with 20 threads
  | Thu May 23 15:29:28 CEST 2024: mgatk successfully processed the supplied bam files
  | Thu May 23 15:29:37 CEST 2024: Successfully created final output files
  | Thu May 23 15:29:37 CEST 2024: Intermediate files successfully removed.
  | Thu May 23 15:38:12 CEST 2024: Starting analysis with mgatk
  | Thu May 23 15:38:12 CEST 2024: Processing samples with 20 threads
  | Thu May 23 15:38:12 CEST 2024: mgatk successfully processed the supplied .bam files
  | Thu May 23 15:38:17 CEST 2024: Successfully created final output files
  | Thu May 23 15:38:17 CEST 2024: Intermediate files successfully removed.

**Post an ls -lRh of mgatk_output_folder**
`ls -IRh
final logs qc
`

**Describe the sequencing assay being analyzed**
The data was produced using the 10x multiome ATAC + RNA, and the Dogma seq protocol. Looking at the QC there were ~15% Mt reads

**Clarify if the execution successful on the test data provided in the repository**
I haven't tried this yet

**Additional context**
Extra context. This is running inside a singularity VM.

**Comment by tybottorff** [comment]
I got a very similar error using `mgatk call` for bulk ATACseq data if @davhg96 you resolved this perhaps

**Comment by danieljrichard** [comment]
This I believe is a bug with 'pulp' - where the newer version has changed the name of a function. 
The solution I found working was to down-grade pulp
pip3 install --force-reinstall -v "pulp==2.7"
##confim we down-graded successfully
pip freeze

Now I'm running into different issues though

**Comment by caleblareau** [comment]
Hi-- we recently released `mgatk v0.9.0` that should address this. Could you give it a try and see if this fixes the issue?
